name: CI
on: [push]
jobs:
  commits:
    name: Commitlint
    runs-on: ubuntu-latest
    container: practically/conventional-tools:1.x
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: {fetch-depth: 1000}

      - name: Git safe.directory
        run: git config --global --add safe.directory $PWD

      - name: Lint commits
        run: conventional-tools commitlint -l1

  test:
    name: Test Node ${{ matrix.node-versions }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-versions: ['14', '16', '18']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-versions }}

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test
